[package]
authors = ["Eirik Albrigtsen <sszynrae@gmail.com>"]
name = "tournament"
version = "0.1.0"

[dependencies]
clap = "2.2.1"
serde = "1.0.11"
serde_derive = "1.0.14"
serde_json = "1.0.3"

[lib]
name = "tournament"
path = "src/lib.rs"
